development:
  adapter: sqlite3
  database: db/owc2011_development.sqlite3

test: &test
  adapter: sqlite3
  database: db/owc2011_test.sqlite3

production:
  adapter: postgresql
  database: owc2011_production

cucumber:
  <<: *test
