development:
  adapter: sqlite3
  database: owc2011_development

test: &test
  adapter: sqlite3
  database: owc2011_test

production:
  adapter: postgresql
  database: owc2011_production

cucumber:
  <<: *test
